Added exits with codes and redirected errors to stderr.

diff --git a/calc b/calc
--- a/calc
+++ b/calc
@@ -2,8 +2,8 @@
 numberCheck='^-?[0-9]+$'
 if ! [[ $2 =~ $numberCheck ]] || ! [[ $3 =~ $numberCheck ]]
 then 
-echo "Third and Fourth arguements should be integer numbers."
-exit
+echo "Third and Fourth arguements should be integer numbers." 1>&2
+exit -1
 fi
 result=0
 if [[ $1 = "sum" ]] 
@@ -19,11 +19,17 @@ then
 let result=$2\*$3 
 else 
 if [[ $1 = "div" ]] 
-then 
+then
+if [[ $3 -eq 0 ]]
+then
+echo "You can't divide by zero." 1>&2
+exit -2
+else 
 let result=$2\/$3
+fi
 else
-echo "Wrong Second Arguement."
-exit 
+echo "Wrong Second Arguement." 1>&2
+exit  -3
 fi
 fi
 fi
diff --git a/interactive b/interactive
--- a/interactive
+++ b/interactive
@@ -81,7 +81,7 @@ if [[ "$insert" = "b" ]] || [[ "$insert" = "Search" ]]
 then
 if [[ $searchFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
 continue
 else
 echo "Insert the name of the directory and a regular expression."
@@ -93,7 +93,7 @@ if [[ "$insert" = "c" ]] || [[ "$insert" = "reverse" ]]
 then
 if [[ $reverseFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
 continue
 else
 echo "Insert two names of the files."
@@ -105,7 +105,7 @@ if [[ "$insert" = "d" ]] || [[ "$insert" = "String length" ]]
 then
 if [[ $strlenFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
 continue
 else
 echo "Insert a line."
@@ -117,7 +117,7 @@ if [[ "$insert" = "e" ]] || [[ "$insert" = "Log" ]]
 then
 if [[ $logFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
 continue
 else
 ./log
@@ -127,11 +127,13 @@ if [[ "$insert" = "g" ]] || [[ "$insert" = "Help" ]]
 then
 if [[ $helpFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
 continue
 else
 ./help
 fi 
+else
+echo "There's no such command, look the menu up." 1>&2
 fi
 fi
 fi
diff --git a/main b/main
--- a/main
+++ b/main
@@ -86,11 +86,13 @@ if [[ "$1" = "search" ]]
 then
 if [[ $searchFlag -eq 0 ]]
 then 
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
+exit -5
 else
 if [[ "$#" -lt 3 ]]
 then
-echo "Not enough arguements."
+echo "Not enough arguements." 1>&2
+exit -6
 else
 ./search $2 $3
 fi
@@ -100,11 +102,13 @@ if [[ "$1" = "reverse" ]]
 then
 if [[ $reverseFlag -eq 0 ]]
 then 
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
+exit -5
 else
 if [[ "$#" -lt 3 ]]
 then 
-echo "Not enough arguements."
+echo "Not enough arguements." 1>&2
+exit -6
 else
 ./reverse $2 $3
 fi
@@ -114,11 +118,13 @@ if [[ "$1" = "strlen" ]]
 then
 if [[ $strlenFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
+exit -5
 else
 if [[ "$#" -lt 2 ]]
 then
-echo "Not enough arguements."
+echo "Not enough arguements." 1>&2
+exit -6
 else
 ./strlen $2
 fi
@@ -128,7 +134,8 @@ if [[ "$1" = "log" ]]
 then
 if [[ $logFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
+exit -5
 else
 ./log
 fi
@@ -146,7 +153,8 @@ if [[ "$1" = "help" ]]
 then
 if [[ $helpFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
+exit -5
 else
 ./help
 fi
@@ -154,9 +162,19 @@ else
 if [[ "$1" = "interactive" ]]
 then
 if [[ $interactiveFlag -eq 0 ]]
-then echo "The file is still missing."
+then 
+echo "The file is still missing."
 else
 ./interactive
+fi
+else
+echo "There's no such key. See existing keys in Help." 1>&2
+if [[ $helpFlag -eq 0 ]]
+then 
+echo "Help file is missing." 1>&2
+exit -5
+else
+./help
 fi
 fi
 fi
