Added checking if File Check file is there

diff --git a/interactive b/interactive
--- a/interactive
+++ b/interactive
@@ -11,7 +11,16 @@ ${nl}f. Exit;
 ${nl}g. Help;
 ${nl} Insert the letter or the name of the command. To exit insert Exit or f."
 #Check the files:
+dir="$( dirname "${BASH_SOURCE[0]}")"
+fileName="FileCheck"
+fileExists=$(find "$dir" -name "$fileName")
+if [[ $fileExists ]]
+then
 source FileCheck
+else
+echo "The file check file is missing." 1>&2
+exit -5
+fi
 #Get the command and the arguements. If there's not enough arguements, unlike main the app wouldn't show an error message, since the user was specifically told what to insert.
 while :
 do
diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,6 +1,15 @@
 #!/bin/bash
 #Check the files.
+dir="$( dirname "${BASH_SOURCE[0]}" )"
+fileName="FileCheck"
+fileExists=$(find "$dir" -name "$fileName")
+if [[ $fileExists ]]
+then
 source FileCheck
+else
+echo "The file check file is missing." 1>&2
+exit -5
+fi
 #Get the arguements. If there's not enough arguements or the file is still missing the app will end its work with an error message and a negative exit code.
 if [[ "$1" = "calc" ]]
 then
