Added comments

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,14 +1,18 @@
 #!/bin/bash
+#Check the files.
 source FileCheck
+#Get the arguements. If there's not enough arguements or the file is still missing the app will end its work with an error message and a negative exit code.
 if [[ "$1" = "calc" ]]
 then
 if [[ $calcFlag -eq 0 ]]
 then
-echo "The file is still missing."
+echo "The file is still missing." 1>&2
+exit -5
 else
 if [[ "$#" -lt 4 ]]
 then
-echo "Not enough arguements."
+echo "Not enough arguements." 1>&2
+exit -6
 else
 ./calc $2 $3 $4
 fi
